name: chessmart_rs

services:
  postgres-auth:
    container_name: postgres-auth
    image: postgres:15.3
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  postgres-matchmaking:
    container_name: postgres-matchmaking
    image: postgres:15.3
    environment:
      POSTGRES_DB: matchmaking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_matchmaking_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.2.3-alpine3.18
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ['redis-server', '--requirepass', 'password']

  nats:
    container_name: nats
    image: nats:2.10.6-alpine3.18
    command: ['-js', '-m', '8222', '--user', 'nats', '--pass', 'password', '--store_dir', '/data/js']
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - nats_data:/data/js

  authentication:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RUST_LOG: debug
      DATABASE_URL: postgres://postgres:password@postgres-auth:5432/auth_db
      REDIS_URL: redis://redis:6379
    env_file:
      - ./authentication/.env
    ports:
      - "50051:50051"
    depends_on:
      - postgres-auth
      - redis
    volumes:
      - .:/project
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /project
    # command: ["cargo", "watch", "-x", "run", "-p", "authentication"]
    entrypoint: ["/entrypoint.sh"]

  matchmaking:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RUST_LOG: debug
      DATABASE_URL: postgres://postgres:password@postgres-matchmaking:5432/matchmaking_db
      REDIS_URL: redis://redis:6379
      REDIS_PASSWORD: password
      REDIS_PORT: 6379
      REDIS_HOST: redis
    env_file:
      - ./matchmaking/.env
    ports:
      - "50052:50052"
    depends_on:
      - postgres-matchmaking
      - redis
    volumes:
      - .:/project
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /project
    # command: ["cargo", "watch", "-x", "run", "-p", "matchmaking"]
    entrypoint: ["/entrypoint.sh"]

  game:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RUST_LOG: debug
      NATS_URL: nats://nats:4222
      NATS_USER: nats
      NATS_PASSWORD: password

      REDIS_URL: redis://redis:6379
      REDIS_PASSWORD: password
      REDIS_PORT: 6379
      REDIS_HOST: redis
    env_file:
      - ./game/.env
    ports:
      - "50053:50053"
    depends_on:
      - nats
      - redis
    volumes:
      - .:/project
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /project
    # command: ["cargo", "watch", "-x", "run", "-p", "game"]
    entrypoint: ["/entrypoint.sh"]

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RUST_LOG: debug

      REDIS_URL: redis://redis:6379
      REDIS_PASSWORD: password
      REDIS_PORT: 6379
      REDIS_HOST: redis
    env_file:
      - ./gateway/.env
    ports:
      - "3338:3338"
    depends_on:
      - authentication
      - matchmaking
      - game
      - redis
    volumes:
      - .:/project
      - cargo-cache:/usr/local/cargo/registry
    working_dir: /project
    # command: ["cargo", "run", "-p", "gateway"]
    entrypoint: ["/entrypoint.sh"]

volumes:
  postgres_auth_data:
  postgres_matchmaking_data:
  redis_data:
  nats_data:
  cargo-cache:

networks:
  postgres:
    driver: bridge
