[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12"
tonic = "0.10"
serde = { version = "1.0", features = ["derive"] }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio", "tls-rustls", "migrate", "macros", "uuid", "chrono"] }
redis = { workspace = true, features = ["tokio-comp"] }
thiserror = { workspace = true }

[build-dependencies]
tonic-build = "0.10"
